# Generated by Django 6.0.4 on 2026-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("prediction", models.CharField(max_length=20, null=True)),
                ("confidence", models.FloatField(null=True)),
                ("mean_pixel", models.FloatField(null=True)),
                ("std_pixel", models.FloatField(null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
