# Generated by Django 6.0.4 on 2026-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="batch_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
