# Generated by Django 6.0.4 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_imageanalysis_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="analysis_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
